baseURL = 'https://btorb.github.io/btn-advisory.ch'  # no trailing slash, local: '/'
languageCode = 'en-us'
title = 'BTN Advisory'

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [module.hugoVersion]
    extended = true

[css]
  [css.postcss]
    path = "main.css"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  env = "production"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Cartoons"
    url = "/cartoons/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

ignoreFiles = [
  "themes/hugo-bearblog/layouts/_default/baseof.html",
  "themes/hugo-bearblog/layouts/partials/header.html",
  "themes/hugo-bearblog/layouts/partials/footer.html"
]